# frozen_string_literal: true

# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: creative_seq.proto

require 'google/protobuf'

require '/app/proto/creative_message_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file('creative_seq.proto', syntax: :proto2) do
    add_message 'proto.CreativeSeq' do
      repeated :creatives, :message, 1, 'proto.CreativeMessage'
    end
  end
end

module Proto
  CreativeSeq = ::Google::Protobuf::DescriptorPool.generated_pool.lookup('proto.CreativeSeq').msgclass
end
