# frozen_string_literal: true

# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: creative_message.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file('creative_message.proto', syntax: :proto2) do
    add_message 'proto.CreativeMessage' do
      required :id, :string, 1
      required :price, :float, 2
    end
  end
end

module Proto
  CreativeMessage = ::Google::Protobuf::DescriptorPool.generated_pool.lookup('proto.CreativeMessage').msgclass
end
